name: 🐞 Bug Report
description: Report an unexpected behaviour
title: "[BUG]"
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the observed behavior
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How do you reproduce this? Please provide as much step-by-step detail as possible.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen when the reproduce steps are followed?
      placeholder: Tell us what you expected to see!
    validations:
      required: true

  - type: input
    attributes:
      label: SkArclight Version
      description: Which version of SkArclight are you using?
      placeholder: |
        Ex: "1.0.0"
    validations:
      required: true

  - type: input
    attributes:
      label: Skript Version
      description: Which version of Skript are you using?
      placeholder: |
        Ex: "2.7.1"
    validations:
      required: true

  - type: input
    attributes:
      label: Server Version
      description: Which version of the server and MC are you using?
      placeholder: |
        Ex: "arclight-1.18.2-1.0.9-7a0a1946 (MC: 1.18.2)"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: Any additional information that may help us solve the bug.
      placeholder: |
        Ex: "I am using X mod"
    validations:
      required: false
