name: 👷 Feature Request
description: Request an addition or change to SkArclight
title: "[SUGGESTION]"
body:
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: What would you like to see improved?
      placeholder: |
        The more details, the better
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered
      placeholder: |
        The more details, the better
    validations:
      required: true

  - type: input
    attributes:
      label: Skript Version
      description: Which version of Skript are you using?
      placeholder: |
        Ex: "2.7.1"
    validations:
      required: true

  - type: input
    attributes:
      label: Server Version/Type
      description: Which version/type of the server and Minecraft are you using?
      placeholder: |
        Ex: "arclight-1.18.2-1.0.9-7a0a1946 (MC: 1.18.2)"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any additional information that may help us out.
      placeholder: |
        Ex: "I know that Bukkit has API <link here>"
    validations:
      required: false
